package rambleonevents;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import rambleon.RambleOn;
import static rambleon.RambleOnSettings.*;

/**
 * This class handles events generated by the back to the accounts screen
 * button.
 *
 * @author James Porcelli, SBU ID 108900819
 */
public class BackToAccountsButtonHandler implements ActionListener {

    private RambleOn game;

    /**
     * Creates a new instance of a back to the accounts screen button handler.
     *
     * @param game The game we are making changes to.
     */
    public BackToAccountsButtonHandler(RambleOn game) {
        this.game = game;
    }

    /**
     * Event handling routine for events fired by the back to the accounts
     * screen button.
     *
     * @param e
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        //SAVE THE NEWEST DATA TO TO FILE
        RambleOn.getScreenManager().writeData();

        game.getAudio().play(SUCCESS, false);
        //RESET THE TABLE 
        RambleOn.getScreenManager().resetStatTableCells();
        //AND INIT THE REGIONS PLAYED TREE FOR THE MOST RECENT DATA
        RambleOn.getScreenManager().initRegionsPlayedTree();
        //NOW MINIMIZE THE GAME PLAY SCREEN
        game.getWindow().setVisible(false);
        game.getAudio().stop(TRACKED_SONG);
        //AND MAKE THE ACCOUNTS SCREEN VISIBLE STARTING FROM THE CURRENT ACCOUNT 
        //SCREEN
        RambleOn.getScreenManager().gotoAccountsManager();
        RambleOn.getScreenManager().refreshWindow();
    }
}
